<?php

$replace_stmt = $dbh->prepare("REPLACE INTO $Project->project_table (
	icp,icpcreationdate,icpcommisiondate,eventstart,eventend,auditnumber,connection,reconcilliation,dedicatednsp,installation,proposedretailer,umldist,networkuserref,networkpricingaudit,distpricecat,distlosscat,chargeablecapacity,reference,reconciliationauditnumber,retailer,profile,reconciliationuserreference,meteringaudit,metercontact,category,metertypehhr,metertypenhh,metertypeunm,metertypepp,ami,dailyunmeteredkwh,unmeteredretailer,meterregister,metermultiplier,meteruserref,statusaudit,icpstatus,icpstatusreason,statususerref,addressaudit,addressunit,addressnumber,addressregion,addressstreet,addresstown,  
addresspostcode,addressuserref,gps_easting,gps_northing,poc,shared_icp_list,direct_billed_details,generationcapacity,generationfueltype,initial_energisationdate,networkidentifier,directbilledstatus,directbilleddetails,anzsic,proposedmep,unmflag,unmloadtrader,switchInProgressMEP,switchInProgress,submissionTypeHHR,submissionTypeNHH,propertyname)
VALUES (:icp, :icpcreationdate, :icpcommisiondate, :eventstart, :eventend, :auditnumber, :connection, :reconcilliation, :dedicatednsp, :installation, :proposedretailer, :umldist, :networkuserref, :networkpricingaudit, :distpricecat, :distlosscat, :chargeablecapacity, :reference, :reconciliationauditnumber, :retailer, :profile, :reconciliationuserreference, :meteringaudit, :metercontact, :category, :metertypehhr, :metertypenhh, :metertypeunm, :metertypepp, :ami, :dailyunmeteredkwh, :unmeteredretailer, :meterregister, :metermultiplier, :meteruserref, :statusaudit, :icpstatus, :icpstatusreason, :statususerref, :addressaudit, :addressunit, :addressnumber, :addressregion, :addressstreet, :addresstown,   
 :addresspostcode, :addressuserref, :gps_easting, :gps_northing, :poc, :shared_icp_list, :direct_billed_details, :generationcapacity, :generationfueltype, :initial_energisationdate, :networkidentifier, :directbilledstatus, :directbilleddetails,  :anzsic, :proposedmep, :unmflag, :unmloadtrader, :switchInProgressMEP, :switchInProgress ,:submissionTypeHHR,:submissionTypeNHH,:propertyname) on duplicate key update ");
 

$test_stmt = $dbh->prepare("update $Project->project_table set icp = :icp , icpcreationdate = :icpcreationdate");

/*create project */



$sql = "INSERT INTO $Project->project_table( icp , icpcreationdate , icpcommisiondate , eventstart , eventend , auditnumber , connection , reconcilliation , dedicatednsp , installation , proposedretailer , umldist , networkuserref , networkpricingaudit , distpricecat , distlosscat , chargeablecapacity , reference , reconciliationauditnumber , retailer , profile , reconciliationuserreference , meteringaudit , metercontact , category , metertypehhr , metertypenhh , metertypeunm , metertypepp , ami , dailyunmeteredkwh , unmeteredretailer , meterregister , metermultiplier , meteruserref , statusaudit , icpstatus , icpstatusreason , statususerref , addressaudit , addressunit , addressnumber , addressregion , addressstreet , addresstown , addresspostcode , addressuserref , gps_easting , gps_northing , poc , shared_icp_list , direct_billed_details , generationcapacity , generationfueltype , initial_energisationdate , networkidentifier , directbilledstatus , directbilleddetails , anzsic , proposedmep , unmflag , unmloadtrader , switchInProgressMEP , switchInProgress , installdetails ,submissionTypeHHR,submissionTypeNHH,propertyname) VALUES ( :icp , :icpcreationdate , :icpcommisiondate , :eventstart , :eventend , :auditnumber , :connection , :reconcilliation , :dedicatednsp , :installation , :proposedretailer , :umldist , :networkuserref , :networkpricingaudit , :distpricecat , :distlosscat , :chargeablecapacity , :reference , :reconciliationauditnumber , :retailer , :profile , :reconciliationuserreference , :meteringaudit , :metercontact , :category , :metertypehhr , :metertypenhh , :metertypeunm , :metertypepp , :ami , :dailyunmeteredkwh , :unmeteredretailer , :meterregister , :metermultiplier , :meteruserref , :statusaudit , :icpstatus , :icpstatusreason , :statususerref , :addressaudit , :addressunit , :addressnumber , :addressregion , :addressstreet , :addresstown , :addresspostcode , :addressuserref , :gps_easting , :gps_northing , :poc , :shared_icp_list , :direct_billed_details , :generationcapacity , :generationfueltype , :initial_energisationdate , :networkidentifier , :directbilledstatus , :directbilleddetails , :anzsic , :proposedmep , :unmflag , :unmloadtrader , :switchInProgressMEP , :switchInProgress , :installdetails ,:submissionTypeHHR,:submissionTypeNHH,:propertyname) 
on duplicate key update  icpcreationdate  = values(icpcreationdate),  icpcommisiondate  = values(icpcommisiondate),  eventstart  = values(eventstart),  eventend  = values(eventend),  auditnumber  = values(auditnumber),  connection  = values(connection),  reconcilliation  = values(reconcilliation),  dedicatednsp  = values(dedicatednsp),  installation  = values(installation),  proposedretailer  = values(proposedretailer),  umldist  = values(umldist),  networkuserref  = values(networkuserref),  networkpricingaudit  = values(networkpricingaudit),  distpricecat  = values(distpricecat),  distlosscat  = values(distlosscat),  chargeablecapacity  = values(chargeablecapacity),  reference  = values(reference),  reconciliationauditnumber  = values(reconciliationauditnumber),  retailer  = values(retailer),  profile  = values(profile),  reconciliationuserreference  = values(reconciliationuserreference),  meteringaudit  = values(meteringaudit),  metercontact  = values(metercontact),  category  = values(category),  metertypehhr  = values(metertypehhr),  metertypenhh  = values(metertypenhh),  metertypeunm  = values(metertypeunm),  metertypepp  = values(metertypepp),  ami  = values(ami),  dailyunmeteredkwh  = values(dailyunmeteredkwh),  unmeteredretailer  = values(unmeteredretailer),  meterregister  = values(meterregister),  metermultiplier  = values(metermultiplier),  meteruserref  = values(meteruserref),  statusaudit  = values(statusaudit),  icpstatus  = values(icpstatus),  icpstatusreason  = values(icpstatusreason),  statususerref  = values(statususerref),  addressaudit  = values(addressaudit),  addressunit  = values(addressunit),  addressnumber  = values(addressnumber),  addressregion  = values(addressregion),  addressstreet  = values(addressstreet),  addresstown  = values(addresstown),  addresspostcode  = values(addresspostcode),  addressuserref  = values(addressuserref),  gps_easting  = values(gps_easting),  gps_northing  = values(gps_northing),  poc  = values(poc),  shared_icp_list  = values(shared_icp_list),  direct_billed_details  = values(direct_billed_details),  generationcapacity  = values(generationcapacity),  generationfueltype  = values(generationfueltype),  initial_energisationdate  = values(initial_energisationdate),  networkidentifier  = values(networkidentifier),  directbilledstatus  = values(directbilledstatus),  directbilleddetails  = values(directbilleddetails),  anzsic  = values(anzsic),  proposedmep  = values(proposedmep),  unmflag  = values(unmflag),  unmloadtrader  = values(unmloadtrader),  switchInProgressMEP  = values(switchInProgressMEP),  switchInProgress  = values(switchInProgress),  installdetails  = values(installdetails) , submissionTypeHHR = values(submissionTypeHHR), submissionTypeNHH = values(submissionTypeNHH), propertyname = values(propertyname)";



$manual_statement = "insert into $Project->project_table (icp, icpcreationdate, auditnumber, connection) VALUES( :icp, :icpcreationdate, :auditnumber,:connection ) on duplicate key update 
icpcreationdate=values(icpcreationdate), auditnumber=values(auditnumber), connection= values(connection)";

$stmt = $dbh->prepare($sql);

?>
